config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("myaudioshare.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

myaudioshare/users/urls.py
from django.urls import path

from myaudioshare.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

books/models.py
from django.db import models
from positions import PositionField


# Create your models here.
from common.models import CommonPropertiesModel


class Narrator(CommonPropertiesModel):
    name = models.CharField(max_length=50)


class Author(CommonPropertiesModel):
    books = models.ManyToManyField('Book', blank=True)


class Series(CommonPropertiesModel):
    description = models.TextField(blank=True, null=True)


class Book(CommonPropertiesModel):
    name = None
    title = models.CharField(max_length=100)
    description = models.TextField()
    book_number = PositionField(unique_for_field='series')
    narrators = models.ManyToManyField(Narrator)
    series = models.ForeignKey(Series, on_delete=models.PROTECT)
    public = models.BooleanField(default=True)


class Image(CommonPropertiesModel):
    name = None
    tags = None
    image = models.ImageField(upload_to="Images")
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class AudioFile(CommonPropertiesModel):
    name = None
    tags = None
    audio_file = models.FileField(upload_to='AudioFiles')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


class Genre(CommonPropertiesModel):
    description = models.TextField(blank=True, null=True)
    books = models.ManyToManyField(Book, blank=True)

common/models.py
from django.db import models
from tagulous import models as tagulous_models


# Create your models here.
from myaudioshare.users.models import User


class Tags(tagulous_models.TagTreeModel):
    class TagMeta:
        force_lowercase = True
        # TODO: define autocomplete view, e.g.:
        # autocomplete_view = 'food.views.tag_autocomplete'


class CommonPropertiesModel(models.Model):
    name = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        related_name='%(app_label)s_%(class)s_created_by',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    updated_date = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        related_name='%(app_label)s_%(class)s_updated_by',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    tags = tagulous_models.TagField(to=Tags)
    active = models.BooleanField(default=True)

    def __iter__(self):
        field_names = [(f.name, f.verbose_name) for f in self._meta.fields]
        field_names += [(f.name, f.verbose_name) for f in self._meta.many_to_many]
        field_names = [(f.name, f.verbose_name, f,) for f in self._meta.fields]
        field_names += [(f.name, f.verbose_name, f,) for f in self._meta.many_to_many]
        for field_name in field_names:
            value = getattr(self, field_name[0], None)
            if isinstance(field_name[2], models.ManyToManyField):
                vs = []
                for v in value.all():
                    vs.append(v)
                value = vs
            yield (field_name[1], value)

    class Meta:
        abstract = True

myaudioshare/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

myaudioshare/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

books/views.py
from django.shortcuts import render

# Create your views here.

common/views.py
from django.shortcuts import render

# Create your views here.

myaudioshare/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

myaudioshare/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

myaudioshare/templates/_nav.html
{% load i18n %}

<div class="m-b-1">

  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">My Audio Share</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li
          class="nav-item {% if request.resolver_match.url_name == 'about' %}active{% endif %}">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <li
            class="nav-item {% if request.resolver_match.url_name == 'detail' %}active{% endif %}">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link"
               href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
          </li>
          <li
            class="nav-item {% if request.resolver_match.url_name == 'account_logout' %}active{% endif %}">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
          {% if request.user.is_superuser %}
            <li
              class="nav-item {% if request.resolver_match.url_name == 'admin' %}active{% endif %}">
              <a id="log-in-link" class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>
            </li>
          {% endif %}
        {% else %}
          <li
            class="nav-item {% if request.resolver_match.url_name == 'account_signup' %}active{% endif %}">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link"
               href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li
            class="nav-item {% if request.resolver_match.url_name == 'account_login' %}active{% endif %}">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link"
               href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

</div>

myaudioshare/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}MyAudioShare{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

  {% include "_nav.html" %}

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

myaudioshare/templates/pages/about.html
{% extends "base.html" %}

myaudioshare/templates/pages/home.html
{% extends "base.html" %}

myaudioshare/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

myaudioshare/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

myaudioshare/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}